---
metadata:
  name: GitBook Starter
  short_name: GitBook
  description: Example Gitbook
  language: en
  pathPrefix: "/"
  siteImage:
  docsLocation: https://github.com/filipowm/gatsby-gitbook-starter
  docsLocationType: github
  editable: true
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: ""
  logoLink: "/"
  helpUrl: ""
  links:
    - text: GitBook
      link: https://github.com/filipowm/gatsby-gitbook-starter
      external: true
    - text: Gatsby
      link: https://www.gatsbyjs.org
      external: true
    - text: Docs
      link: "/"
      external: false
sidebar:
  enabled: true
  forcedNavOrder:
    - "/introduction"
    - "/configuration/basic"
    - "/configuration/advanced"
  expanded:
  groups:
    - order: 1
      path: "/configuration"
      icon: "/assets/settings.svg"
      title: Configuration
    - order: 2
      path: "/syntax"
      icon: "/assets/code.svg"
      title: "Syntax"
    - order: 3
      path: "/developing"
      title: ":computer: Developing"
  links:
    - text: Gitbook
      link: https://github.com/filipowm/gatsby-gitbook-starter
    - text: React
      link: https://reactjs.org
  ignoreIndex: true
  poweredBy:
    trademark: "/assets/gatsby.png"
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: use-credentials
    icons:
      - src: src/pwa-512.png
        sizes: 512x512
        type: image/png
features:
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  toc:
    depth: 3
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  scrollTop: true
  showMetadata: true
  propagateNetlifyEnv: true
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/advanced/theme"
      - regex: "^/syntax"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 300
    height: 300
  rss:
    enabled: true
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Category 1
      - Category 2
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "gidocs"
  darkMode:
    enabled: true  
    default: false

