name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown
        uses: avto-dev/markdown-lint@v1.2.0
        with:
          config: '.mdlint.yml'
          args: '**/*.md'

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
      - name: Dockerfile
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          level: warning

  gatsby:
    name: Build Gatsby site
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: '{path}/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build starter
      run: |
        npm install -g gatsby-cli
        yarn
        npm run build

  docker:
    name: Build Docker images 
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['Dockerfile.builder', 'Dockerfile.runtime', 'Dockerfile.develop']
   
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: filipowm
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: filipowm/gatsby-gitbook-starter
        tags: latest
        tag_with_ref: true
        tag_with_sha: false 
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: ${{ matrix.dockerfile }}
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: false # optional, default is true 
