name: CI
on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown
        uses: avto-dev/markdown-lint@v1.2.0
        with:
          config: '.mdlint.yml'
          args: '**/*.md'

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
      - name: Dockerfile
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          level: warning

  netlify:
    name: Build and Deploy preview on Netlify
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Waiting for 300sec from the Netlify preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor300
        with:
          site_name: "boogi"
          max_timeout: 300
      - name: Netlify deploy logs
        uses: bdougie/loglify@master  

  docker:
    name: Build Docker images 
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['Dockerfile.builder', 'Dockerfile.runtime', 'Dockerfile.develop']
   
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: filipowm
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: filipowm/boogi
        tags: latest
        tag_with_ref: true
        tag_with_sha: false 
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: docker/${{ matrix.dockerfile }}
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: false # optional, default is true 
