name: Release
on:
  push:
    branches:
      - master

jobs:

  release:
    name: Update changelog and create release
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    
    - name: Conventional Changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        output-file: 'CHANGELOG.md'
        tag-prefix: 'v'
        release-count: 0
        package-json: './package.json'

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}

    - name: Sync Github info from release
      uses: jaid/action-sync-node-meta@v1.4.0
      with:
        direction: overwrite-github
        githubToken: ${{ secrets.priv_github_token }}

    - name: Sync develop with master
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "master"
        destination_branch: "develop"
        pr_title: "Synchronize develop with master after release ${{ steps.changelog.outputs.tag }}"
        pr_body: ":crown:"
        pr_reviewer: "filipowm"
        pr_assignee: "filipowm"
        pr_label: "auto-pr"                              
        github_token: ${{ secrets.GITHUB_TOKEN }}